name: Update DB

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run npm update script
        run: npm run update
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Check for changes
        id: git-status
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"
          git status --porcelain
          if [[ $(git status --porcelain) ]]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit and push changes
        if: steps.git-status.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "Auto update DB"
          git push origin HEAD:master